### ISSUE TITLE
Build failing on Jetson Xavier NX with Jetpack 5.0.2

### ISSUE THREAD

**Issue by nakai-omer** [NVIDIA-ISAAC-ROS/isaac_ros_nitros#10]
Hi,

We are getting the following error trying to build this packages on our Jetson:
```
Starting >>> isaac_ros_nitros
--- stderr: isaac_ros_nitros                             
/usr/bin/ld:/home/nakai/develop/nakai/packages/nakai-onboard/src/isaac_ros_nitros/isaac_ros_nitros/gxf/lib/gxf_jetpack502/core/libgxf_core.so: file format not recognized; treating as linker script
/usr/bin/ld:/home/nakai/develop/nakai/packages/nakai-onboard/src/isaac_ros_nitros/isaac_ros_nitros/gxf/lib/gxf_jetpack502/core/libgxf_core.so:1: syntax error
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/isaac_ros_nitros.dir/build.make:311: libisaac_ros_nitros.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/isaac_ros_nitros.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
---
```

lsb release:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

kernel:
```
Linux ubuntu 5.10.104-tegra #1 SMP PREEMPT Wed Aug 10 20:17:07 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by nakai-omer** [comment]
Found the answer, `git lfs` needs to be installed, and then run `git lfs pull` to fetch the large files.

**Comment by eladpar** [comment]
@hemalshahNV 
Can we add it into the readme or installation process?
Got stuck with this too

**Comment by hemalshahNV** [comment]
We do mention `git-lfs` as a prerequisite because it is easy to forget but we can try to make this more explicit and see if we can add a warning.

**Comment by nakai-omer** [comment]
@hemalshahNV I couldn't find git-lfs anywhere in the readme

**Comment by hemalshahNV** [comment]
We added to the Dev Env setup guide ([here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/docs/dev-env-setup.md)) to include running `git lfs install` which we run for you as part of the Docker image but if you don't, you'll need to run it yourself. Thanks for pointing this out!
