### ISSUE TITLE
 undefined reference to `nvtxRangePushEx` and `nvtxRangePop`

### ISSUE THREAD

**Issue by Vulcan-YJX** [NVIDIA-ISAAC-ROS/isaac_ros_nitros#17]
when I use cuvslam with hawk , get a error about isaac_ros_image_proc can't find `nvtxRangePushEx` and `nvtxRangePop` in the libisaac_ros_nitros_image_type.so.

- hardware : jetson orin agx 
- system : Jetpack 5.1.1
- camera : LI-AR0234CS-STEREO-GMSL2
`--- stderr: isaac_ros_image_proc`                                          
`/usr/bin/ld: dp_ws/install/isaac_ros_nitros_image_type/lib/libisaac_ros_nitros_image_type.so: undefined reference to nvtxRangePushEx`
`/usr/bin/ld: dp_ws/install/isaac_ros_nitros_image_type/lib/libisaac_ros_nitros_image_type.so: undefined reference to nvtxRangePop`
How do I fix it？

Thanks.

**Comment by hemalshahNV** [comment]
The latest release of Isaac ROS is DP3. The Isaac ROS Dev container adds `/usr/local/cuda-11.4/targets/aarch64-linux/lib` to your LD_LIBRARY_PATH which would resolve this.

**Comment by Vulcan-YJX** [comment]
I use this command,but it not works.
`export LD_LIBRARY_PATH="/usr/local/cuda-11.4/targets/aarch64-linux/lib:${LD_LIBRARY_PATH}"`

**Comment by Vulcan-YJX** [comment]
Thanks. it works.
