### ISSUE TITLE
Cannot locate rosdep definition for [negotiated]

### ISSUE THREAD

**Issue by RailWar** [NVIDIA-ISAAC-ROS/isaac_ros_nitros#2]
I can not build package. I got the message "isaac_ros_nitros: Cannot locate rosdep definition for [negotiated]"
I have ROS2 Humble with last packages.

**Comment by hemalshahNV** [comment]
The `negotiated` package from Open Robotics is not yet in bloom so rosdep does not find it. We build it for you as part of the Isaac ROS Common base container (see Dockerfile.humble [here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/ae66a08fd852a994db08fd53f74b82940aacca96/docker/Dockerfile.humble#L133) for how).

**Comment by omerts** [comment]
@hemalshahNV Is there any non-docker solution for this?

**Comment by hemalshahNV** [comment]
You can build it as part of your own ROS workspace or you can try building it in `/opt/ros/humble/src` with the merge-install option that will work for a source install (basically what the Docker image does) and may work with the binary install of ROS2 Humble (have not tried).
