### ISSUE TITLE
problem building ros_nitros for library dependency problem

### ISSUE THREAD

**Issue by TeamRoboTo** [NVIDIA-ISAAC-ROS/isaac_ros_nitros#21]
Hello everyone,
i had this problem while building this package on my jetson AGX Xavier inside the docker, can you help me ? 
thanks in advantage for your time!

![image](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nitros/assets/107797173/12e2d3c3-242f-4ccb-ac65-e4557ff430eb)

**Comment by jaiveersinghNV** [comment]
The relevant header file is included from the `Negotiated` ROS 2 package that should be included with an install of ROS 2 Humble. The package is also included inside our Isaac ROS Dev containers, which we recommend that you use for development with Isaac ROS.

Can you check if your system has the package installed?
```bash
$ ros2 pkg prefix negotiated
/opt/ros/humble/install
```

**Comment by fxprime** [comment]
Same issue here.
Can we just install that package by ourself?

**Comment by jaiveersinghNV** [comment]
@fxprime , I've responded to your thread [here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline/issues/31#issuecomment-1577568449). We provide a pre-built version of this package as part of our Isaac ROS Docker containers. If you're running outside of a container, you will need to built the package yourself.
