### ISSUE TITLE
Header common/unique_index_map.hpp not found

### ISSUE THREAD

**Issue by ShanPoon** [NVIDIA-ISAAC-ROS/isaac_ros_nitros#29]
When I compile package **isaac_ros_nitros_imu_type**, the following error occurs

--- stderr: isaac_ros_nitros_imu_type                             
In file included from /workspaces/isaac_ros-dev/src/isaac_ros_nitros/isaac_ros_nitros_type/isaac_ros_nitros_imu_type/src/nitros_imu.cpp:15:
/workspaces/isaac_ros-dev/install/share/isaac_ros_gxf/gxf/include/gxf/isaac_messages/gems/pose_tree/pose_tree.hpp:21:10: fatal error: common/unique_index_map.hpp: No such file or directory
   21 | #include "common/unique_index_map.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I have checked the packages, the **common/unique_index_map.hpp** is present to the outer layer of the folder. It is believed that the **common** folder is not properly included (**pose_tree.hpp** layer exists a common folder with **pose_frame_uid.hpp** only) 
![Screenshot from 2023-09-11 10-11-45](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nitros/assets/88710086/dce8551a-55b7-4b89-9e09-1073c137fbd1)

This error exists in Docker x86_64 build only. When I build with Docker aarch64, it succeeds. 
This problem will affect other isaac_ros_nitrons_type such as **isaac_ros_nitros_point_cloud_type**, **isaac_ros_nitros_imu_type** and **isaac_ros_nitros_flat_scan_type** as they need to include the same header **gems/pose_tree/pose_tree.hpp**

Anyone can help how to fix this issue? Thanks

**Comment by swapnesh-wani-nvidia** [comment]
Hello, could you confirm if you have the latest code checked out? I am not able to reproduce this issue on my end, however, try clearing out the colon build-cache `rm -r build install log` from your ROS workspace.
