### ISSUE TITLE
Can't compile Nitros x86_64 with ros rolling class rclcpp::GuardCondition’ has no member named ‘add_to_wait_set

### ISSUE THREAD

**Issue by jpalves** [NVIDIA-ISAAC-ROS/isaac_ros_nitros#30]
nitros_publisher.cpp:94:20: error: ‘class rclcpp::GuardCondition’ has no member named ‘add_to_wait_set’
   94 |   guard_condition_.add_to_wait_set(wait_set);

Ubuntu 20.04
ROS Rolling

**Comment by swapnesh-wani-nvidia** [comment]
Hello, `isaac_ros_nitros` is supported on ROS2 Humble. Could you elaborate on the need to use the Rolling version?
