### ISSUE TITLE
isaac_ros_nitros_image_type/src/nitros_image.cpp

### ISSUE THREAD

**Issue by GeorgeNegret** [NVIDIA-ISAAC-ROS/isaac_ros_nitros#7]
I think line 30 from nitros_image.cpp  
#include "sensor_msgs/sensor_msgs/image_encodings.hpp"   
should be changed to : 
#include "sensor_msgs/image_encodings.hpp"

**Comment by hemalshahNV** [comment]
Good catch. When building ROS2 from source, however, the header files for `sensor_msgs` end up in `/opt/ros/humble/install/include/sensor_msgs/sensor_msgs/image_encodings.hpp`. We haven't investigated why that happens yet but it leads to the awkward include there.

**Comment by nakai-omer** [comment]
@hemalshahNV I think this should be re-opened, as this causes this repo to fail building for anyone not building ROS2 from source

**Comment by hemalshahNV** [comment]
That's fair. With some symlinks this could be worked around for a binary install of ROS2 Humble. Isaac ROS only supports Ubuntu 20.04 at the moment (as of DP2.1) on both x86_64 and Jetson which is a Tier 3 platform for ROS2 Humble (source compatibility only, no binaries). We will need to figure this out as part of Jammy support.
